version: "3"

services:
  tomcat:
    image: tomcat:9
    container_name: tomcat-container
    user: root
    ports:
      - "8082:8080"
    volumes:
      - jenkins-data:/usr/local/tomcat/

  jenkins:
    image: jenkins/jenkins:jdk17
    container_name: jenkins-container
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/app/dev/jenkins_home

volumes:
  jenkins-data:
