version: "3"

services:
  tomcat:
    image: tomcat:9
    container_name: tomcat-container
    ports:
      - "8082:8080"
    networks:
      - my-network
    volumes:
      - jenkins-data:/usr/local/tomcat/

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-container
    ports:
      - "8080:8080"
    networks:
      - my-network
    volumes:
      - jenkins-data:/var/jenkins_home

networks:
  my-network:
    driver: bridge

volumes:
  jenkins-data:
